feeds:
  - https://www.theguardian.com/uk/lifeandstyle/rss
  - https://www.theguardian.com/lifeandstyle/health-and-wellbeing/rss
  - https://www.theguardian.com/games/rss
  - https://www.theguardian.com/uk/film/rss
  - https://www.theguardian.com/music/rss
  - https://www.theguardian.com/uk/travel/rss
