feeds:
  - https://practicaldatamodeling.substack.com/feed
  - https://newsletter.pragmaticengineer.com/feed
  - https://marvelousmlops.substack.com/feed
  - https://www.decodingai.com/feed
  - https://mettlesome.substack.com/feed



